name: Run Tests and Generate Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm run core:test:coverage
      
      # - name: Generate coverage badges
      #   run: npx jest-coverage-badges
      
      # - name: Commit coverage badges
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: 'coverage/'
      #     message: 'chore: update coverage badges'
      #     push: true 